"""empty message

Revision ID: 84f3832a9e84
Revises: 
Create Date: 2021-06-19 13:25:20.680176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84f3832a9e84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('scale', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=60), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('thumbnail', sa.String(length=256), nullable=True),
    sa.Column('bg', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('logo', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('name')
    )
    op.create_table('experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.String(length=20), nullable=False),
    sa.Column('finish_date', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homepage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('background_image', sa.String(length=256), nullable=True),
    sa.Column('short_note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_email', sa.String(length=128), nullable=False),
    sa.Column('postage_date', sa.DateTime(), nullable=True),
    sa.Column('subject', sa.String(length=128), nullable=False),
    sa.Column('msg', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('homepage')
    op.drop_table('experiences')
    op.drop_table('contacts')
    op.drop_table('admin')
    op.drop_table('abilities')
    # ### end Alembic commands ###
