"""empty message

Revision ID: 8dcd1eff4c27
Revises: 84f3832a9e84
Create Date: 2021-06-19 13:30:11.898692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dcd1eff4c27'
down_revision = '84f3832a9e84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('homepage')
    op.add_column('experiences', sa.Column('title', sa.String(length=60), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiences', 'title')
    op.create_table('homepage',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('background_image', sa.VARCHAR(length=256), nullable=True),
    sa.Column('short_note', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
